In [2]:
import pandas as pd

from openbi.model.dataset import Dataset
from openbi.model.table import Table
from openbi.pipeline.pipeline_builder import DefaultPipeline

# ---------------------------------------
# Create Dataset
# ---------------------------------------

dataset = Dataset(name="Retail Sales")

# ---------------------------------------
# Load Excel
# ---------------------------------------

df = pd.read_excel("../examples/sales.xlsx")

print("Original Data")
display(df)

# ---------------------------------------
# Execute Pipeline
# ---------------------------------------

pipeline = DefaultPipeline.create()

result = pipeline.execute(df)

stats = result.statistics

clean_df = result.dataframe



print("Cleaned Data")
display(clean_df)

# ---------------------------------------
# Create Table
# ---------------------------------------

orders = Table.from_dataframe(
    name="Orders",
    dataframe=clean_df
)

dataset.model.add_table(orders)

# ---------------------------------------
# Verify
# ---------------------------------------



for step in stats.steps:

    print(step.step_name)

    print("Rows Before :", step.rows_before)

    print("Rows After  :", step.rows_after)

    print("Changed     :", step.values_changed)

    print("Time (ms)   :", step.execution_time_ms)

    print("-" * 40)

print()
print("Pipeline Statistics")
print("-------------------")

print("Rows Before :", stats.rows_before)
print("Rows After  :", stats.rows_after)

print("Columns     :", stats.columns_after)

print("Execution   :", stats.total_execution_time_ms)

Original Data

   OrderId   OrderDate   Amount
0    NS-101 2026-04-06  10200.0
1    NS-102 2026-04-07  21002.0
2    NS-103 2026-04-08  21002.0
3    NS-104 2026-04-09  21002.0
4    NS-105 2026-04-10  21002.0
5    NS-106 2026-04-11  21202.0
6    NS-107 2026-04-12  21302.0
7    NS-108 2026-04-13  21002.0
8    NS-109 2026-04-14  21402.0
9    NS-110 2026-04-15      NaN
10   NS-111 2026-04-15  21002.0
11   NS-112 2026-04-17  21002.0
12   NS-113 2026-04-18  21002.0
13   NS-114 2026-04-19  21002.0
14   NS-115 2026-04-20  21502.0
15   NS-115 2026-04-20  21502.0
16   NS-116 2026-04-21  21002.0
17   NS-117 2026-04-22  21002.0
18   NS-118 2026-04-23      NaN
19   NS-119 2026-04-24  21002.0
20   NS-120 2026-04-25  21002.0

Cleaned Data

   OrderId   OrderDate   Amount
0    NS-101 2026-04-06  10200.0
1    NS-102 2026-04-07  21002.0
2    NS-103 2026-04-08  21002.0
3    NS-104 2026-04-09  21002.0
4    NS-105 2026-04-10  21002.0
5    NS-106 2026-04-11  21202.0
6    NS-107 2026-04-12  21302.0
7    NS-108 2026-04-13  21002.0
8    NS-109 2026-04-14  21402.0
9    NS-111 2026-04-15  21002.0
10   NS-112 2026-04-17  21002.0
11   NS-113 2026-04-18  21002.0
12   NS-114 2026-04-19  21002.0
13   NS-115 2026-04-20  21502.0
14   NS-116 2026-04-21  21002.0
15   NS-117 2026-04-22  21002.0
16   NS-119 2026-04-24  21002.0
17   NS-120 2026-04-25  21002.0

Whitespace Cleaner
Rows Before : 21
Rows After  : 21
Changed     : 0
Time (ms)   : 4.667099998187041
----------------------------------------
String Cleaner
Rows Before : 21
Rows After  : 21
Changed     : 0
Time (ms)   : 3.7210000009508803
----------------------------------------
Date Normalizer
Rows Before : 21
Rows After  : 21
Changed     : 0
Time (ms)   : 17.188800000440096
----------------------------------------
Null Handler
Rows Before : 21
Rows After  : 19
Changed     : 2
Time (ms)   : 2.3225000004458707
----------------------------------------
Duplicate Remover
Rows Before : 19
Rows After  : 18
Changed     : 1
Time (ms)   : 1.4171000002534129
----------------------------------------
Type Converter
Rows Before : 18
Rows After  : 18
Changed     : 0
Time (ms)   : 2.5077000027522445
----------------------------------------

Pipeline Statistics
-------------------
Rows Before : 21
Rows After  : 18
Columns     : 3
Execution   : 32.023100000515115