In [2]:
import pandas as pd

from openbi.model.dataset import Dataset
from openbi.model.table import Table
from openbi.pipeline.pipeline_builder import DefaultPipeline

# ---------------------------------------
# Create Dataset
# ---------------------------------------

dataset = Dataset(name="Retail Sales")

# ---------------------------------------
# Load Excel
# ---------------------------------------

df = pd.read_excel("../examples/sales.xlsx")

print("Original Data")
display(df)

# ---------------------------------------
# Execute Pipeline
# ---------------------------------------

pipeline = DefaultPipeline.create()

result = pipeline.execute(df)

clean_df = result.dataframe

print("Cleaned Data")
display(clean_df)

# ---------------------------------------
# Create Table
# ---------------------------------------

orders = Table.from_dataframe(
    name="Orders",
    dataframe=clean_df
)

dataset.model.add_table(orders)

# ---------------------------------------
# Verify
# ---------------------------------------

print("Dataset :", dataset.name)
print("Rows    :", orders.row_count)
print("Columns :", orders.column_count)

Original Data

   OrderId   OrderDate   Amount
0    NS-101 2026-04-06  10200.0
1    NS-102 2026-04-07  21002.0
2    NS-103 2026-04-08  21002.0
3    NS-104 2026-04-09  21002.0
4    NS-105 2026-04-10  21002.0
5    NS-106 2026-04-11  21202.0
6    NS-107 2026-04-12  21302.0
7    NS-108 2026-04-13  21002.0
8    NS-109 2026-04-14  21402.0
9    NS-110 2026-04-15      NaN
10   NS-111 2026-04-16  21002.0
11   NS-112 2026-04-17  21002.0
12   NS-113 2026-04-18  21002.0
13   NS-114 2026-04-19  21002.0
14   NS-115 2026-04-20  21502.0
15   NS-116 2026-04-21  21002.0
16   NS-117 2026-04-22  21002.0
17   NS-118 2026-04-23      NaN
18   NS-119 2026-04-24  21002.0
19   NS-120 2026-04-25  21002.0

[Whitespace Cleaner] 0.004s
[String Cleaner] 0.002s
[Date Normalizer] 0.009s
[Null Handler] 0.002s
[Duplicate Remover] 0.009s
[Type Converter] 0.001s
Cleaned Data

   OrderId   OrderDate  Amount
0    NS-101 2026-04-06   10200
1    NS-102 2026-04-07   21002
2    NS-103 2026-04-08   21002
3    NS-104 2026-04-09   21002
4    NS-105 2026-04-10   21002
5    NS-106 2026-04-11   21202
6    NS-107 2026-04-12   21302
7    NS-108 2026-04-13   21002
8    NS-109 2026-04-14   21402
10   NS-111 2026-04-16   21002
11   NS-112 2026-04-17   21002
12   NS-113 2026-04-18   21002
13   NS-114 2026-04-19   21002
14   NS-115 2026-04-20   21502
15   NS-116 2026-04-21   21002
16   NS-117 2026-04-22   21002
18   NS-119 2026-04-24   21002
19   NS-120 2026-04-25   21002

Dataset : Retail Sales
Rows    : 18
Columns : 3